import type { Metadata } from "next";
import { Gabarito, Lexend } from "next/font/google";
import "./globals.css";

const gabarito = Gabarito({
	variable: "--font-gabarito",
	subsets: ["latin"],
});

const lexend = Lexend({
	variable: "--font-lexend",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${gabarito.variable} ${lexend.variable} font-sans antialiased w-screen h-screen bg-slate-600`}
			>
				{children}
			</body>
		</html>
	);
}
